name: events
services:
  database:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=events
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../.containers/events-db:/var/lib/postgresql/data
    ports:
      - 5432:5432